{{- $deviceHostPath := default .Values.zigbee2mqtt.zigbee_device .Values.zigbee2mqtt.device.hostPath -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zigbee2mqtt.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "zigbee2mqtt.fullname" . }}
  replicas: {{ .Values.zigbee2mqtt.replicaCount }}
  {{- with .Values.zigbee2mqtt.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "zigbee2mqtt.selectorLabels" . | nindent 8 }}
        {{- with .Values.zigbee2mqtt.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.zigbee2mqtt.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if or .Values.zigbee2mqtt.serviceAccount.create .Values.zigbee2mqtt.serviceAccount.name }}
      serviceAccountName: {{ include "zigbee2mqtt.serviceAccountName" . }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.zigbee2mqtt.serviceAccount.automount }}
      {{- with .Values.zigbee2mqtt.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zigbee2mqtt.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init
          image: {{ include "zigbee2mqtt.image" . | quote }}
          imagePullPolicy: {{ .Values.zigbee2mqtt.image.pullPolicy }}
          command: ["sh"]
          args:
            - -c
            - "{{- if .Values.zigbee2mqtt.overwriteConfig -}}cp /configuration.yaml /app/data/{{- else -}}[ -f /app/data/configuration.yaml ] || cp /configuration.yaml /app/data/{{- end -}}"
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: config
              mountPath: /configuration.yaml
              subPath: configuration.yaml
      {{- with .Values.zigbee2mqtt.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zigbee2mqtt.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.zigbee2mqtt.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          {{- with .Values.zigbee2mqtt.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "zigbee2mqtt.image" . | quote }}
          imagePullPolicy: {{ .Values.zigbee2mqtt.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: data
              mountPath: /app/data
            {{- if .Values.zigbee2mqtt.udev.enabled }}
            - name: udev
              mountPath: {{ .Values.zigbee2mqtt.udev.mountPath }}
              readOnly: {{ .Values.zigbee2mqtt.udev.readOnly }}
            {{- end }}
            - name: zigbee-device
              mountPath: {{ .Values.zigbee2mqtt.device.mountPath }}
            {{- with .Values.zigbee2mqtt.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          env:
            - name: TZ
              value: "{{ .Values.zigbee2mqtt.timezone }}"
            {{- with .Values.zigbee2mqtt.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.zigbee2mqtt.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zigbee2mqtt.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zigbee2mqtt.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zigbee2mqtt.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zigbee2mqtt.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        {{- if .Values.zigbee2mqtt.udev.enabled }}
        - name: udev
          hostPath:
            path: {{ .Values.zigbee2mqtt.udev.hostPath | quote }}
            {{- with .Values.zigbee2mqtt.udev.hostPathType }}
            type: {{ . }}
            {{- end }}
        {{- end }}
        - name: zigbee-device
          hostPath:
            path: {{ $deviceHostPath | quote }}
            {{- with .Values.zigbee2mqtt.device.hostPathType }}
            type: {{ . }}
            {{- end }}
        - name: config
          {{- if .Values.zigbee2mqtt.existingConfigSecret.name }}
          secret:
            secretName: {{ .Values.zigbee2mqtt.existingConfigSecret.name }}
            items:
              - key: {{ .Values.zigbee2mqtt.existingConfigSecret.key }}
                path: configuration.yaml
          {{- else }}
          configMap:
            name: {{ printf "%s-config" (include "zigbee2mqtt.fullname" .) }}
          {{- end }}
        {{- if not .Values.zigbee2mqtt.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- else if .Values.zigbee2mqtt.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.zigbee2mqtt.persistence.existingClaim }}
        {{- end }}
        {{- with .Values.zigbee2mqtt.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if and .Values.zigbee2mqtt.persistence.enabled (not .Values.zigbee2mqtt.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.zigbee2mqtt.persistence.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.zigbee2mqtt.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.zigbee2mqtt.persistence.accessModes | nindent 10 }}
        {{- if .Values.zigbee2mqtt.persistence.storageClassName }}
        {{- if eq .Values.zigbee2mqtt.persistence.storageClassName "-" }}
        storageClassName: ""
        {{- else }}
        storageClassName: {{ .Values.zigbee2mqtt.persistence.storageClassName | quote }}
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.zigbee2mqtt.persistence.size }}
  {{- end }}
