name: CI

on:
  pull_request:
  workflow_call:

concurrency:
  group: chart-ci-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

env:
  CHART_NAME: zigbee2mqtt

jobs:
  validate:
    name: Chart tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310
        with:
          version: v3.19.0
      - uses: helm/chart-testing-action@6ec842c01de15ebb84c8627d2744a0c2f2755c9f # v2.8.0
      - name: Lint chart
        run: ct lint --charts "charts/$CHART_NAME"
      - uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc
      - name: Install chart and run Helm tests
        run: ct install --charts "charts/$CHART_NAME" --helm-extra-args "--timeout 5m"
